### ISSUE TITLE
Permission needs to be explicitly asked for from SDK version 23

### ISSUE THREAD

**Issue by aknoerig** [Integreight/1Sheeld-Android-SDK#1]
The provided sample code from the README does no longer work when using Android SDK version 23 or newer. Since the required `permission android.permission.ACCESS_COARSE_LOCATION` is rated _dangerous_, the app needs to explicitly ask the user to grant it. Otherwise the app will fail to connect (and unfortunatelty silently so).

See https://developer.android.com/training/permissions/requesting.html for how to ask the user for permission.

**Comment by isso** [comment]
Hi @aknoerig , thank you for your feedback. :)

We are aware of that issue and we made it clear in the README file that this permission is required for Bluetooth discovery starting from Android 6.0 (API v23).

It is the application developer (the one who uses our SDK) job to ask users to grant dangerous permissions in runtime.

The sample app is still [targeting Android SDK v22](https://github.com/Integreight/1Sheeld-Android-SDK/blob/master/sampleApplication/build.gradle), so that shouldn't be a problem because the location permission wasn't dangerous back then and didn't require explicit grant from the user.

I'm currently in the process of upgrading both 1Sheeld app and SDK repos to support Android Nougat (API v24) and I'll revisit the sample code implementation to do a simple example of how to request the dangerous location permission in runtime while maintaining the app's simplicity.

**Comment by aknoerig** [comment]
Hi @iSsO, thanks for the additional info. I guess I'd leave this issue open until the sample code is updated then – or at least add a note to the readme?

**Comment by isso** [comment]
Hi @aknoerig, the sample app and the SDK have been [updated](https://github.com/Integreight/1Sheeld-Android-SDK/releases/tag/v2.1.4) (v2.1.4), they are targeting Android Nougat (API v24) now and the sample app asks users to grant the dangerous location permission prior to scanning. I've also added an additional note regarding that in the readme.

If you have additional feedback, please don't hesitate reopening the issue. :)
